Add scala3doc to the community suite and fix a number of issues
scalameta/scalameta pull request #2148
Opened 2020-10-23 15:08 UTC by tgodzik

2020-10-23 15:16 UTC, tgodzik commented on scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
> +          } else if (curr.is[EOF]) {
We weren't adding outdents when EOF was met, which can easily happen.

2020-10-23 15:16 UTC, tgodzik commented on scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
> +      case _ if isParams && token.is[NonParamsModifier] => mods
This allows naming params `transparent` `opaque` etc.

2020-10-23 15:16 UTC, tgodzik commented on tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
> +  test("given-anon-as") {
So this one currently works in Dotty, reported it as weird here https://github.com/lampepfl/dotty/issues/10074

2020-10-23 15:16 UTC, tgodzik commented on scalameta/trees/shared/src/main/scala/scala/meta/internal/trees/ParentChecks.scala
> +    parent.is[Type] || parent.is[Defn.Type]
`type Tuple = [X] =>> (X, X)`

2020-10-23 15:16 UTC, tgodzik commented on tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/SignificantIndentationSuite.scala
> +                  |  def y: String = { fa(); fb() }""".stripMargin
This is on purpose to test `EOF` ending an indent

2020-10-23 22:00 UTC, kpbochenek requested changes
Inline comment is only blocking, rest as you wish :)

Good work! Nice to see community-tests growing :smile:

2020-10-23 23:02 UTC, kpbochenek commented on community-test/src/test/scala/CommunityDottySuite.scala
> +    // def (s: String).doesntStartWithAnyOfThese(c: Char*) = c.forall(char => !s.startsWith(char.toString))
it doesn't compile in latest scala3 repl I think

2020-10-24 10:17 UTC, tgodzik commented on community-test/src/test/scala/CommunityDottySuite.scala
> +    // val result: List[Int] = fmap[F = List, A = Int, B = Int](List(1,2,3))(i => i + 1)
We can try to fix it later on if needed. I will leave it for now.

2020-10-24 10:18 UTC, tgodzik commented on scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
> +          } else if (curr.is[EOF]) {
I don't think people usually leave EOF, but it failed on a number of places in scala3doc

2020-10-24 10:20 UTC, tgodzik commented on tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/GivenUsingSuite.scala
> +  test("given-anon-as") {
Added!

2020-10-24 10:21 UTC, tgodzik commented on community-test/src/test/scala/CommunityDottySuite.scala
> +    // extension.getParameters.asScala(extension.get(MethodExtension).parametersListSizes(0))
yes, that's the problem. It should be fixable, but might require a bit more work and didn't want to add too much to this PR. I will fix it separately.

2020-10-24 10:22 UTC, tgodzik commented on community-test/src/test/scala/CommunityDottySuite.scala
> +    // def (s: String).doesntStartWithAnyOfThese(c: Char*) = c.forall(char => !s.startsWith(char.toString))
Thanks! I didn't know that.

2020-10-24 10:37 UTC, tgodzik commented on community-test/src/test/scala/CommunityDottySuite.scala
> +    // def (s: String).doesntStartWithAnyOfThese(c: Char*) = c.forall(char => !s.startsWith(char.toString))
Just checked, you are right. Marked it as such.

2020-10-24 10:42 UTC, tgodzik commented on tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/MinorDottySuite.scala
> +  test("opaque-soft-keyword") {
Haha, yeah, there are problematic for sure. I think it would be possible to solve it better, but I think it's too late for that.

2020-10-24 10:45 UTC, tgodzik commented on scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
> +      isSoftKw(token, SoftKeyword.SkTransparent) || isSoftKw(token, SoftKeyword.SkInline)
It's still working, because inline is being checked earlier. Removed anyway, since that could indeed be problematic later.

2020-10-24 10:46 UTC, tgodzik commented on community-test/src/test/scala/CommunityDottySuite.scala
> +  final def scala3DocExclusionList = List(
Added `[scalameta]` to any issues we still need to fix.

2020-10-24 17:11 UTC, kpbochenek commented
once again good work, LGTM! :+1:

2020-10-24 17:12 UTC, kpbochenek approved these changes
once again good work, LGTM! :+1:

2020-10-26 12:24 UTC, merged