Change extension to be a soft keyword again
scalameta/scalameta pull request #2199
Opened 2020-12-21 19:13 UTC by tgodzik

Previously, when discussing https://github.com/lampepfl/dotty/issues/10076 it was mentioned that `extension` would become
a keyword, but turns out it will not be. I kind of jumped the gun here and we should not have chanegd it until it was in
the compiler code.

2020-12-22 10:02 UTC, kpbochenek requested changes
not happy we have to go back to it being softKW, but at least it sounds like final decision.

Good job monitoring those changes in compiler :+1:

2020-12-22 10:11 UTC, tgodzik commented on tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala
> +    val code = """|extension (c: Circle)
It's not really optional :/

```
[error] -- Error: /home/tgodzik/Documents/workspaces/dotty-vinz/src/main/scala/Main.scala:10:23 
[error] 10 |    extension (a : Int):
[error]    |                       ^
[error]    |                       no `:` expected here
```

2020-12-22 11:49 UTC, tgodzik commented on tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala
> +
Good catch, it was not actually working. Thanks!

2020-12-22 11:49 UTC, tgodzik commented on tests/shared/src/test/scala/scala/meta/tests/parsers/dotty/ExtensionMethodsSuite.scala
> +    runTestError[Stat](
Added and after some rework it should be fine now.

2020-12-22 11:54 UTC, tgodzik commented on scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
> +  private val soft = new SoftKeywords(dialect, (token: Token) => token.next)
next is needed to make sure that `[` or `(` is actually next. Might be problematic to use it in scalafmt, but I think doable? @olafurpg

2020-12-23 10:27 UTC, kpbochenek approved these changes
LGTM :+1:

2020-12-23 11:28 UTC, tgodzik commented on scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala
>        def isAmbiguousWithPatVarType(t: Type.Name, p: Tree): Boolean = {
Yeah, I was kind of afraid it's some magic. Removed it!

2020-12-23 11:33 UTC, merged