Revert "Allow `?` as placeholder as default in Scala213 and Scala212 dialects"
scalameta/scalameta pull request #2756
Opened 2022-05-22 17:18 UTC by blast-hardcheese

Fixes #2751 

This reverts commit 817b016b656a683378187d8937bea7c1526e53f5.

This is the first of two PRs, first to temporarily revert this breaking change to 2.12 and 2.13 dialects, the second will be to re-establish the new defaults, intended to be merged once 2.12.16 and 2.13.9 are released.

2022-05-22 17:37 UTC, smarter commented
It looks like the problem isn't that the syntax is allowed, but that it is used by default by the pretty-printer when it is allowed, maybe the pretty-printer could be changed to not do that on Scala 2 (or even better, use token-level information to know whether a ? or an _ should be pretty-printed?)

2022-05-22 18:55 UTC, blast-hardcheese commented
@smarter Right -- This change wasn't incorrect, it was just merged and released before the requisite versions of scalac were released.

Attempting to represent whether `?` or `_` was in the initial encoding would be another way to work around this, though I still think giving control to the `Dialect` responsible for choosing how it's rendered is still the more robust solution. By having Dialect supplied at the end of the world, users wouldn't need to special-case every time a token is constructed.

2022-05-22 18:56 UTC, blast-hardcheese commented
(see #2758)

2022-05-23 05:19 UTC, kitbellew requested changes
honestly, i don't really understand why this is needed. you can provide a different dialect to `.syntax` if you wish. and i already commented on how to avoid this problem with a custom dialect (forgoing quasiquotes).

2022-05-23 10:44 UTC, tgodzik commented
Thanks for the contribution! What would you say about having an alternative approach here: https://github.com/scalameta/scalameta/pull/2759

I think this would be the safest we can do :thinking:

2022-05-23 20:14 UTC, closed without merging

2022-05-23 20:14 UTC, blast-hardcheese commented
Closing in favor of the merged PR, I'll see if I still have difficulties after that gets released. Thank you for your assistance!