Avoid ZipException when loading classpath
scalameta/scalameta pull request #2805
Opened 2022-08-17 00:28 UTC by daddykotex

The default classpath behavior should load directories,
or file that are archives (jar or zip), or wildcards should
be ignored.

I'd like to implement this behaviour here: ignoring invalid files

But there are multiple ways at it:

* manual check of the file, it's existence, it's extension
* catching the ZipException and swallow it

Do you have a suggestion on which on I should take? The first one
is more brittle, and we could possibly ignore jar/zip if they don't
have the right extension. Where as the second one could swallow error
that are not related.

I'm coming from https://github.com/scalacenter/scalafix/pull/1646

Current exception

```
java.util.zip.ZipException: zip END header not found
    at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
    at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
    at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
    at java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
    at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
    at java.util.zip.ZipFile.<init>(ZipFile.java:243)
    at java.util.zip.ZipFile.<init>(ZipFile.java:172)
    at java.util.jar.JarFile.<init>(JarFile.java:347)
    at java.util.jar.JarFile.<init>(JarFile.java:318)
    at java.util.jar.JarFile.<init>(JarFile.java:284)
    at scala.meta.internal.classpath.ClasspathIndex$Builder.scala$meta$internal$classpath$ClasspathIndex$Builder$$expandJarEntry(ClasspathIndex.scala:136)
    at scala.meta.internal.classpath.ClasspathIndex$Builder.expandEntry(ClasspathIndex.scala:102)
    at scala.meta.internal.classpath.ClasspathIndex$Builder.$anonfun$result$1(ClasspathIndex.scala:64)
    at scala.meta.internal.classpath.ClasspathIndex$Builder.$anonfun$result$1$adapted(ClasspathIndex.scala:64)
    at scala.collection.immutable.List.foreach(List.scala:431)
    at scala.meta.internal.classpath.ClasspathIndex$Builder.result(ClasspathIndex.scala:64)
    at scala.meta.internal.classpath.ClasspathIndex$.apply(ClasspathIndex.scala:51)
    at scala.meta.tests.metacp.ClasspathIndexSuite.$anonfun$new$38(ClasspathIndexSuite.scala:58)
```

2022-08-17 07:17 UTC, kitbellew commented
i am ok with returning on ZipException in `new JarFile` (but not in subsequent code).

2022-08-19 02:01 UTC, kitbellew requested changes

2022-08-19 03:33 UTC, daddykotex commented on semanticdb/metacp/src/main/scala/scala/meta/internal/classpath/ClasspathIndex.scala
>        try {
I was not sure you would allow `return` usage, and I tried to replicate the style found in other try/catch in the code base

will cleanup

2022-08-19 03:41 UTC, daddykotex commented
Thanks for the review, I appreciate it.

2022-08-19 13:30 UTC, kitbellew approved these changes

2022-08-19 13:34 UTC, merged