ScalametaParser: parse annot args before params
scalameta/scalameta pull request #3034
Opened 2023-01-08 08:29 UTC by kitbellew

Allow annotations before class constructor, meaning annotation could have its arg clauses but has to stop before ctor param clauses. For #2405.

2023-01-08 13:17 UTC, kitbellew commented
@tgodzik how does the compiler handle this case? it can probably tell literal goes to annotation, implicit goes to constructor, default values as well...

except, specifically, the ambiguity between ascribed annotation argument and constructor parameter `(foo: Foo)`? and what's the proper way to use this as a parameter, and not annotation argument?

2023-01-11 13:11 UTC, tgodzik commented
> except, specifically, the ambiguity between ascribed annotation argument and constructor parameter (foo: Foo)? and what's the proper way to use this as a parameter, and not annotation argument?

It doesn't accept type annotated parameters there, this will always be treated as a param. It seems it parses it annotation and those might not accept typed params?

It's somewhere around here:
https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L3702

2023-01-11 13:22 UTC, tgodzik commented
Actually, it seems everything is explained here https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L2586

2023-01-11 13:29 UTC, tgodzik requested changes
Thanks for looking into this! I did some digging and I think I found how it's done in the compiler. The Scala 2 one should handle it the same.

2023-01-13 15:06 UTC, tgodzik approved these changes
LGTM!

2023-01-13 15:21 UTC, kitbellew commented on scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
> +        annotsBuf(buf, skipNewLines = false, allowArgss = false, insidePrimaryCtorAnnot = true)
@tgodzik btw, what is `allowArgss = false` here? if i read the code that you shared correctly, at least dotty allows multiple, not sure about scala2.

2023-01-13 15:35 UTC, merged