bugfix: support carriage return
scalameta/scalameta pull request #3343
Opened 2023-09-18 13:00 UTC by kasiaMarek

connected to: https://github.com/scalameta/metals/issues/5369

2023-09-18 14:09 UTC, kasiaMarek commented on scalameta/inputs/shared/src/main/scala/scala/meta/internal/inputs/InternalInput.scala
> +      else if (lastIsCR) buf += i
Is it enough to say: ```we consider all `\n`, `\r\n` and `\r` as new line```? This is consistent with [most editors](https://en.wikipedia.org/wiki/Comparison_of_text_editors#Newline_support).

2023-09-18 15:30 UTC, kitbellew requested changes
which system generates `\r` without a `\n`? and why? it's definitely not windows and not unix.

scalafmt definitely does not handle this case either. Token.CR is not something anyone looks for.

should we change the underlying system?

2023-09-18 15:30 UTC, kitbellew commented on scalameta/inputs/shared/src/main/scala/scala/meta/internal/inputs/InternalInput.scala
> +      else lastIsCR = false
```suggestion
      lastIsCR = chars(i) == '\r'
```

2023-09-22 14:49 UTC, tgodzik approved these changes
LGTM from me! @kitbellew what do you think?

2023-09-22 15:20 UTC, kitbellew approved these changes

2023-09-22 16:12 UTC, merged