Add mill extension to supported ones
scalameta/scalameta pull request #3989
Opened 2024-10-07 13:43 UTC by lolgab

2024-10-07 13:47 UTC, tgodzik requested changes
Looks good! You will just need to run scalafmt

2024-10-07 15:00 UTC, kitbellew requested changes

2024-10-08 07:53 UTC, tgodzik approved these changes
LGTM!

2024-10-08 09:45 UTC, kitbellew commented on semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/SemanticdbPipeline.scala
> +      val matchesFilter = Option(unit.source.file)
it's still a val and hence will be evaluated every time, including when `!matchesExtension`

2024-10-08 17:11 UTC, kitbellew approved these changes
thank you!

2024-10-08 17:11 UTC, merged